//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salida_empleado
    {
        public int id_salida_empleado { get; set; }
        public string codigo_empleado1 { get; set; }
        public string tipo_salida { get; set; }
        public string motivo { get; set; }
        public string fecha_salida { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
