//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacaciones
    {
        public int id_vacaciones { get; set; }
        public string codigo_empleado2 { get; set; }
        public string desde { get; set; }
        public string hasta { get; set; }
        public string correspondiente { get; set; }
        public string comentario { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
